#$ -cwd
#$ -q sandbox
#$ -pe mpi 16
#$ -S /bin/bash

set -e
set -u
set -o pipefail

module load hisat2/v2.1.0
module load samtools/v1.10

REF=../../References/All_Bacterial_Genomes_v2.fasta
SAMPLE=${PWD##*/}
MATE1=$(ls ../../../00_data/Trimmed/${SAMPLE}/*R1*QC.fastq.gz)
MATE2=$(ls ../../../00_data/Trimmed/${SAMPLE}/*R2*QC.fastq.gz)
NAME=${SAMPLE}_vs_Microbiome

hisat2 --no-unal -p $NSLOTS -x $REF -1 $MATE1 -2 $MATE2 -S ${NAME}.sam

samtools view -@ $NSLOTS -b -o ${NAME}.bam ${NAME}.sam
rm ${NAME}.sam
samtools sort -@ $NSLOTS -o ${NAME}_sorted.bam ${NAME}.bam
rm ${NAME}.bam
samtools index ${NAME}_sorted.bam ${NAME}_sorted.bai
