#$ -cwd
#$ -q high_mem
#$ -pe mpi 32
#$ -S /bin/bash

module load salmon/v1.3.0

SMAR_TRANS=Smar_R05_DeNovo.NoDups.fasta
MAP_PATH=../01_mapping/VsTranscriptome

while read i; do
	SAMPLE=${i}
	echo "Processing sample ${SAMPLE}"
	INFILE=${MAP_PATH}/${SAMPLE}/${SAMPLE}_vs_Transcriptome.bam
	
	salmon quant -t $SMAR_TRANS -l ISR -a $INFILE -p $NSLOTS \
		--gcBias --seqBias -o ${SAMPLE}
done < ../R05.lst
