#$ -cwd
#$ -q sandbox@compute-0-10
#$ -pe mpi 16
#$ -S /bin/bash

set -e
set -u
set -o pipefail

module load hisat2/v2.1.0
module load samtools/v1.10

REF=../../../References/Skeletonema_marinoi_Ref_v1.1.2.fst
SAMPLE=${PWD##*/}
MATE1=$(ls ../../../../00_data/PolyA_Removal/${SAMPLE}/${SAMPLE}.polyAtrim.rRNAdecon.QC_1.fastq)
MATE2=$(ls ../../../../00_data/PolyA_Removal/${SAMPLE}/${SAMPLE}.polyAtrim.rRNAdecon.QC_2.fastq)
NAME=${SAMPLE}_vs_RefGenome.MaxInt10K.NoMixedDiscordant

# no-mixed and no-discordant included as they're used by the Trinity utility script `align_and_estimate_abundance`
hisat2 -p $NSLOTS --no-unal --no-mixed --no-discordant --max-intronlen 10000 -x $REF -1 $MATE1 -2 $MATE2 -S ${NAME}.sam

samtools view -@ $NSLOTS -b -o ${NAME}.bam ${NAME}.sam
rm ${NAME}.sam
samtools sort -@ $NSLOTS -o ${NAME}_sorted.bam ${NAME}.bam
rm ${NAME}.bam
samtools index ${NAME}_sorted.bam ${NAME}_sorted.bai
